pipeline:
  clone:
    image: armhfplugins/git

  docker:
    image: armhfplugins/docker
    username: ${DOCKER_USER}
    email: ${DOCKER_EMAIL}
    password: ${DOCKER_PASSWORD}
    repo: armhfbuild/nginx
    tag: ${DRONE_BRANCH}
