pipeline:
  clone:
    image: armhfplugins/git

  docker:
    image: armhfplugins/docker
    username: ${DOCKER_USER}
    password: ${DOCKER_PASSWORD}
    email: ${DOCKER_EMAIL}
    repo: armhfbuild/nginx
    tags: ${DRONE_BRANCH}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
