pipeline:
  clone:
    image: armhfplugins/git

  docker:
    image: armhfplugins/docker
    username: ${DOCKER_USER}
    password: ${DOCKER_PASSWORD}
    email: ${DOCKER_EMAIL}
    repo: armhfbuild/nginx
    tags: [ "1.11.9", "1.11", "1", "latest" ]
    build_args:
      - NGINX_VERSION=1.11.9
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
